### ISSUE TITLE
Load data error when first init db

### ISSUE THREAD

**Issue by gagaboy** [moqui/moqui-hazelcast#3]
When I first init db with moqui-hazelcast component, there are errors below:
`
--- 2017-10-31 13:46:12.278 [   RequireNewTx] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed update with SQL [INSERT INTO LOCALIZED_MESSAGE (ORIGINAL, LOCALE, LOCALIZED, LAST_UPDATED_STAMP) VALUES (?, ?, ?, ?)] and parameters [[]] in [0] seconds changing [1] rows
--- 2017-10-31 13:46:12.278 [   RequireNewTx] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 making crud PreparedStatement for SQL: SELECT ORIGINAL, LOCALE, LOCALIZED, LAST_UPDATED_STAMP FROM LOCALIZED_MESSAGE WHERE ORIGINAL=? AND LOCALE=?
--- 2017-10-31 13:46:12.276 [  MoquiWorker-1] ERROR                  org.moqui.impl.entity.EntityCache []
 Suppressed error in entity cache clearing [moqui.basic.LocalizedMessage; create]
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_152-ea]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_152-ea]
	at org.moqui.impl.entity.EntityCache.clearCacheForValueActual(EntityCache.groovy:197) [moqui_temp3872118964218601865WEB-INF_lib_moqui-framework-2.1.1-rc1.jar.:2.1.1-rc1]
	at org.moqui.hazelcast.HazelcastDciTopicToolFactory$EntityCacheListener$_onMessage_closure1.doCall(HazelcastDciTopicToolFactory.groovy:100) [moqui-hazelcast-1.0.1.jar:?]
	at org.moqui.hazelcast.HazelcastDciTopicToolFactory$EntityCacheListener$_onMessage_closure1.call(HazelcastDciTopicToolFactory.groovy) [moqui-hazelcast-1.0.1.jar:?]
	at org.moqui.impl.context.ExecutionContextImpl$ThreadPoolRunnable.run(ExecutionContextImpl.java:261) [moqui_temp3872118964218601865WEB-INF_lib_moqui-framework-2.1.1-rc1.jar.:2.1.1-rc1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_152-ea]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_152-ea]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152-ea]
--- 2017-10-31 13:46:12.289 [   RequireNewTx] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed query with SQL [SELECT ORIGINAL, LOCALE, LOCALIZED, LAST_UPDATED_STAMP FROM LOCALIZED_MESSAGE WHERE ORIGINAL=? AND LOCALE=?] and parameters [[original:Delete, locale:it]] in [0] seconds
` 
But if not use this component, it runs well. And I have not idea why this happen ?

**Comment by jonesde** [comment]
I've never run into this particular concurrency issue (even with hazelcast in place), but have seen other similar ones in other parts of the caching code. Try this with commit 2749742d in moqui-framework, based on your stack trace that should fix it.

**Comment by gagaboy** [comment]
Sorry,it is not a bug for this component, but cause by some incorrect seed data in my project.
